name: alethic-ism-monitor
channels:
  - file:///app/conda/env/local_channel
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - pyyaml
#  - pulsar-client
  - pydantic
  - restrictedpython
  - nats-py
  - alethic-ism-core
  - alethic-ism-db
