apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-monitor-secret
  namespace: alethic
stringData:
  LOG_LEVEL: "DEBUG"
  DATABASE_URL: "postgresql://ism_db_user:ism_db_user@alethic-db-service:5432/ism_db"
  MSG_URL: "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650"
  MSG_TOPIC: "ism_monitor"
  MSG_MANAGE_TOPIC: "ism_monitor_manage"
  MSG_TOPIC_SUBSCRIPTION: "ism_monitor_subscription"

